### ISSUE TITLE
Juju - Broken Dependencies for libboost

### ISSUE THREAD

**Issue by ghost** [thomnico/juju-nfv-demo#28]
Hi Team,

I am trying to deploy Clearwater and Facing the below error while deploying any of the projects,

Looks like some challenge with the repository while deploying on ubuntu precise,

Its happening with all the versions of Juju

root@juju-ost-machine-29:~# cat /var/chef-solo/chef-stacktrace.out
Generated at 2016-05-18 03:30:16 +0000
Chef::Exceptions::Exec: package[clearwater-snmp-alarm-agent](clearwater::alarms line 35) had an error: Chef::Exceptions::Exec: apt-get -q -y --force-yes install clearwater-snmp-alarm-agent=1.0-160513.165438 returned 100, expected 0
---- Begin output of apt-get -q -y --force-yes install clearwater-snmp-alarm-agent=1.0-160513.165438 ----
STDOUT: Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 clearwater-snmp-alarm-agent : Depends: clearwater-snmpd but it is not going to be installed
                               Depends: libboost-filesystem1.54.0 but it is not installableSTDERR: E: Unable to correct problems, you have held broken packages.
---- End output of apt-get -q -y --force-yes install clearwater-snmp-alarm-agent=1.0-160513.165438 ----

/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/mixin/command.rb:128:in `handle_command_failures'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/mixin/command.rb:75:in`run_command'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/mixin/command.rb:143:in `run_command_with_systems_locale'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/provider/package/apt.rb:97:in`install_package'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/provider/package.rb:82:in `block in action_install'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/mixin/why_run.rb:52:in`call'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/provider.rb:149:in`converge_by'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/provider/package.rb:80:in `action_install'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/provider.rb:114:in`run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/resource.rb:625:in `run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/runner.rb:49:in`run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/runner.rb:81:in`each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/runner.rb:81:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/resource_collection.rb:98:in`block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/resource_collection/stepable_iterator.rb:116:in`call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/resource_collection/stepable_iterator.rb:104:in`iterate'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/resource_collection.rb:96:in`execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/client.rb:429:in`converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/client.rb:494:in `do_run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/client.rb:199:in`block in run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/client.rb:193:in `fork'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/client.rb:193:in`run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/application.rb:183:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/application/solo.rb:239:in`block in run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/application/solo.rb:231:in `loop'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/application/solo.rb:231:in`run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/application.rb:66:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/bin/chef-solo:25:in`<top (required)>'
/usr/bin/chef-solo:23:in `load'

Kindly suggest if there is anything which can be done, 

Or if there is any latest repository which I can use,

Best Regards,
Subhranshu

**Comment by dtyunin** [comment]
Hello, Subhranshu! I faced problem similar to yours and have the same logs. Do you have successful  solution of this issue? And if so, could you be so kind to share your approach that helps you. In all cases, positive or negative, your answer will helps a lot!

Kind Regards,
Dmitry

**Comment by ghost** [comment]
Hi Dmitry,

I am sorry I am coming back a little late as I was on vacation and was unable to check my mails and probably you would have got some solution for it by now and if not then lets work it out here:

I had one more link where I worked with Mir and solved it there, kindly refer to it once and let me know if that solves your problem: https://github.com/Metaswitch/clearwater-juju/issues/42

Best Regards,
Subhranshu

**Comment by dtyunin** [comment]
Hi again, Subhranshu! I really appreciate your help.
We have deployed OpenStack with help of Juju ( `1.25.5-trusty-amd64` ), well-written bundle config file with `juju-deployer` and MAAS. So after that i launch instance in the cloud  for juju client (`2.0-beta12-xenial-amd64`) and bootstrapped openstack from here.

My goal was to deploy Clearwater IMS from bundle. But as i understand all repos in juju charms store are out-of-date, so i tried to checkout [clearwater-juju](https://github.com/Metaswitch/clearwater-juju) and were playing with its branches. After some experiments i found successful combination.
I used:
1. `Juju 2.0-beta12-xenial-amd64`
2. Ubuntu Precise `12.04.5` image for instances( i was tried `12.04.4`, but in my case juju can't raise up instances. Juju agent can't fetch tools from controller node due to error: "`curl: (35) error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version`" . Such behavior has led to the eternal "pending" status of juju workagent )
3.  [Release-100 tag](https://github.com/Metaswitch/clearwater-juju/releases/tag/release-100) of CW IMS. I rewrite bundle.yaml to make it executable by juju deploy command because it seems that juju 2.0 could work only with local paths like this "`charm: ../../../precise/clearwater-sprout`"
4. Also I faced out install hook failure of DNS charm ( this issue very well described by @mirw here [here](https://github.com/chuckbutler/DNS-Charm/issues/29). I fixed this installing python-dns and python-jinja2 packages by hands as advised @mirw 

As a result, Clearwater works and I can make SIP calls through it.
Big thanks for your response!

**Comment by mirw** [comment]
Nice one!

Just FYI on point 3, I saw this too and have applied it to https://github.com/Metaswitch/clearwater-juju/tree/trusty.

**Comment by ghost** [comment]
That Sounds Like a Grandeur ....
